// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxELbeHzN90KtbCf4VDmPX66VIIv1y8I',
    appId: '1:965711969294:web:d16ccd0a43d380e727d05f',
    messagingSenderId: '965711969294',
    projectId: 'fuse-f78ec',
    authDomain: 'fuse-f78ec.firebaseapp.com',
    storageBucket: 'fuse-f78ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSIFFyxZF_xm9vEZlFxBwj6m9XLrI6r1I',
    appId: '1:965711969294:android:7a0ab8e6854d55e927d05f',
    messagingSenderId: '965711969294',
    projectId: 'fuse-f78ec',
    storageBucket: 'fuse-f78ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYfS-AVfOtOxEDowb9lskOtK36RVSml4',
    appId: '1:965711969294:ios:1ae126192450bcc627d05f',
    messagingSenderId: '965711969294',
    projectId: 'fuse-f78ec',
    storageBucket: 'fuse-f78ec.firebasestorage.app',
    iosBundleId: 'com.shindzika.fuse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfYfS-AVfOtOxEDowb9lskOtK36RVSml4',
    appId: '1:965711969294:ios:62807e1da0c8055227d05f',
    messagingSenderId: '965711969294',
    projectId: 'fuse-f78ec',
    storageBucket: 'fuse-f78ec.firebasestorage.app',
    iosBundleId: 'com.example.fuse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxxELbeHzN90KtbCf4VDmPX66VIIv1y8I',
    appId: '1:965711969294:web:5a959e100ba474ef27d05f',
    messagingSenderId: '965711969294',
    projectId: 'fuse-f78ec',
    authDomain: 'fuse-f78ec.firebaseapp.com',
    storageBucket: 'fuse-f78ec.firebasestorage.app',
  );
}
